[package]
name = "searcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21",  features = ["derive"] }
glob = "0.3.1"
regex = "1.10.6"
stop-words = "0.8.0"
walkdir = "2.5.0"
